services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airfloww
      POSTGRES_DB: airflow

    volumnes:
      - postgres-db-volume:/var/lib/postgresql/data
    healtchek:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always


docker run -it \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v $(pwd)/ny_taxi_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  postgres:13

# pgcli -h localhost -p 5432 -u root -d ny_taxi

# if doesn't run
# sudo lsof -i :5432
# sudo kill -9 <pid>
# sudo lsof -i :5432

# https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page
